language: haskell

before_install:
  - mkdir -p ~/.local/bin/stack
  - export PATH=~/.local/bin/stack:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.1.2/stack-1.1.2-linux-x86_64.tar.gz | tar -xzf- -C ~/.local/bin/stack --strip-components=1
  - chmod a+x ~/.local/bin/stack/stack
  - cabal update
  - cabal install happy
  - cabal clean
  - nvm install 5.9.0
  - nvm use 5.9.0

cache:
  directories:
    - $HOME/.stack/

install:
  - stack setup --no-terminal
  - stack build -j1 --only-dependencies --no-terminal

script:
  - stack build -j1 --only-dependencies --no-terminal

sudo: false
