name:                rampart-web
version:             0.0.1
synopsis:            Web experiments with haskell
description:         Discovery of Haskell as a web language
homepage:            https://example.com
license:             BSD3
license-file:        LICENSE
author:              Jan-Philip Loos
maintainer:          jloos@maxdaten.io
copyright:           2016 Jan-Philip Loos
category:            Web

ghc-options:         -threaded -rtsopts -with-rtsopts=-N

executables:
    reflex-starter:
        source-dirs: src
        main: Main.hs
        dependencies:
            - base
            - reflex >= 0.4.0
            - reflex-dom >= 0.3

github: maxdaten/rampart-web
